# Generated by Django 2.2 on 2019-04-24 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=13),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='otp_1',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='otp_2',
            field=models.IntegerField(blank=True),
        ),
    ]
