# Generated by Django 2.2 on 2019-04-24 17:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_auto_20190424_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='file',
            field=models.FileField(upload_to='transaction_files/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=('jpg', 'png', 'pdf', 'jpeg', 'doc', 'docx', 'txt', 'odt', 'odp', 'ods', 'xls', 'xlsx', 'ppt', 'pptx', 'rtf'))]),
        ),
    ]
